site_name: PamDx Data Analysis Guide
docs_dir: docs


theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
